name: Flutter CI

on:
  push:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - name: Build APK
        run: flutter build apk --release --split-per-abi
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: schoolmanagement-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: schoolmanagement-armeabi-v7a-release
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: schoolmanagement-x86_64-release
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
